### ISSUE TITLE
Problem with compile

### ISSUE THREAD

**Issue by Marama651** [TitleOS/StoreBot#1]
Hello. I am unable to build this git. I got error message: 
Error	NETSDK1004	Assets file 'C:\Users\trr\Desktop\kk4\StoreBot-master\StoreBot\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	StoreBot	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	

Any help ?

**Comment by TitleOS** [comment]
Run a NuGet package restore
