### ISSUE TITLE
Package downloads occasionally will lack a proper file name/extension

### ISSUE THREAD

**Issue by TitleOS** [TitleOS/StoreBot#2]
Occasionally, FE3 links gathered by StoreBot will provide files without proper package names or the package extension. The file will be instead named a unique guid, it is unclear if this is a bug with FE3 and or StoreBot/StoreLib. This may be due to an inconsistent "Content-Disposition" header.

**Comment by tunip3** [comment]
this appears to be an issue with FE3 as rg-adguard faces the same issues

**Comment by TitleOS** [comment]
Problem appears to be on Microsoft's side due to other tools facing similar issues, nothing I can do so closing.
